---
# This playbook configures a client to
# connect to avantra master

- name: Install Avantra Client
  hosts: all
  become: true
  vars:
          # avantra_version: "21.11"
          # defaults file for server
          - avantra_client_install_base_dir: /opt/avantra

  tasks:
    - name: ensure download  "{{ avantra_client_install_base_dir }}" exists
      file:
         path: "{{ avantra_client_install_base_dir }}"
         state: directory
         mode: '0755'
         owner: root
         group: root
      tags:
        - download_software

    - name: download avantra client software from storage bucket {{ gcp_bucket_avantra }}
      command:
        cmd: "gsutil cp gs://{{ gcp_bucket_avantra }}/{{ avantra_version }}/agent-{{ avantra_version }}*/agent-*.bin  {{ avantra_client_install_base_dir }}"
        creates: "{{ avantra_client_install_base_dir }}/avantra-client-*linux.bin"
      tags:
        - download_software

    - name: Install Avantra Client
      include_role:
          name: avantra_client_install
      tags:
        - install_software
