---
# tasks file for avantra_client_install

- name: "Ensure Prerequisites are installed"
  dnf:
    name:
      - libnsl2
      - java-1.8.0-openjdk
    state: present

- name: find newest installer
  shell: |
     set -o pipefail
     export LANG=C
     ls -1 agent-*.bin | sort -rV | head -1
  args:
    chdir: "{{ avantra_client_install_base_dir }}"
  changed_when: false
  register: __avantra_client_installer_binary

- name: print Installer version
  debug:
          msg: "Found installer version: {{ __avantra_client_installer_binary.stdout[:-4].split('-').1 }}"

- name: ensure installer is executable
  file:
    path: "{{ avantra_client_install_base_dir }}/{{ __avantra_client_installer_binary.stdout }}"
    state: file
    mode: '0755'
    owner: root
    group: root

- name: wait for avantra server to be up and running (fails after 5 minutes)
  wait_for:
    port: 9050
    host: "{{ avantra_client_install_masterhost }}"
    timeout: 360

- name: run installer
  command:
    cmd: >
       ./{{ __avantra_client_installer_binary.stdout }} --
       --masterhost={{ avantra_client_install_masterhost }}
       --custid={{ avantra_client_install_custid }}
       {{ avantra_client_install_extra_parameter }} --silent
    chdir: "{{ avantra_client_install_base_dir }}"
    # creates: ....
